### ISSUE TITLE
reauths every request when configured with mod_authnz_pam

### ISSUE THREAD

**Issue by laserfox** [modauthgssapi/mod_auth_gssapi#29] opened 2015-05-13 10:28 UTC
When mod_auth_gssapi is configured alongside mod_authnz_pam and GssapiUseSessions, the session appears to be ignored and every request requires authentication.

config:

<Location />
 AuthType GSSAPI
 AuthName "GSSAPI Single Sign On Login"
 GssapiCredStore keytab:/etc/httpd/rt.keytab
 GssapiLocalName on
 GssapiUseSessions On
 Session On
 SessionCookieName gssapi_session path=/;httponly;secure;
 GssapiSessionKey key:{redacted}
 Require pam-account rtir
</Location>

**Comment by simo5** [comment] 2015-06-16 17:50
Thank you for reporting this.
I just tested this configuration, and can't reproduce with the latest code.
Would you be able to try again with current master ?

**Comment by simo5** [comment] 2015-07-04 14:35
Ok, please reopen if it happens again, closing for now.

**Closed by simo5** 2015-07-04 14:35 UTC
