### ISSUE TITLE
Problem with DirectoryIndex

### ISSUE THREAD

**Issue by obma** [modauthgssapi/mod_auth_gssapi#17] opened 2015-04-02 21:37 UTC
Hi!

I want to restrict access to a virtual host with mod_auth_gssapi. The problem is, that if I enable the authentication the default index.php is not provided anymore. Following messages show up in the -error.log:
```
[Thu Apr 02 23:26:07.535887 2015] [core:error] [pid 22578] [client 192.168.12.198:56044] AH00027: No authentication done but request not allowed without authentication for /index.php. Authentication not configured?
[Thu Apr 02 23:26:07.536216 2015] [core:error] [pid 22578] [client 192.168.12.198:56044] AH00027: No authentication done but request not allowed without authentication for /index.phtml. Authentication not configured?
[Thu Apr 02 23:26:07.536343 2015] [core:error] [pid 22578] [client 192.168.12.198:56044] AH00027: No authentication done but request not allowed without authentication for /index.html. Authentication not configured?
```
If I call index.php directly, everything works fine. Also if I disable authentication the DirectoryIndex works as expected.

Here's my vhost-config:
```
<VirtualHost ttrss.example.com:80>
             ServerName ttrss.example.com
             ServerAlias ttrss
             Redirect permanent / https://ttrss.example.com
</VirtualHost>

<VirtualHost ttrss.example.com:443>
    ServerName ttrss.example.com
    ServerAlias ttrss
    ServerAdmin webmin@example.com

    SSLEngine on
    SSLCertificateFile "/etc/httpd/conf/server.crt"
    SSLCertificateKeyFile "/etc/httpd/conf/server.key"

    ErrorLog "/var/log/httpd/ttrss.example.com-error_log"
    CustomLog "/var/log/httpd/ttrss.example.com-access_log" common

    DocumentRoot "/srv/http.ttrss.example.com"

    <Directory "/srv/http.ttrss.example.com">
               AuthType GSSAPI
               AuthName "Single Sign On Login"
               GssapiCredStore keytab:/etc/httpd/conf/vhosts/ttrss.example.com.keytab
               GssapiSSLonly On
               GssapiBasicAuth On
               Require valid-user
    </Directory>
    <Location /api>
              Allow from all
              Satisfy Any
    </Location>
</VirtualHost>
```

**Comment by simo5** [comment] 2015-04-02 21:59
Duplicate of #15

**Closed** 2015-04-02 21:58 UTC
